// Pipeline: CAUSES OF DEATH (ranked breakdown + trend over time)
//
// Source: the static snapshot the WONDER data pipeline writes to
// /data/mortality.json (see pipeline/). That snapshot is CDC WONDER's
// "Underlying Cause of Death, 1999–2020" (database D76), national, grouped by
// year × the NCHS 113 Selected Causes list, with deaths, population, crude
// rate and age-adjusted rate.
//
// This replaces the earlier data.cdc.gov Socrata source (dataset bi63-dtpu),
// which only ran through 2017 and had no crude rate. The snapshot is served
// same-origin as a plain file — no API call, no CORS, no key.
//
// The 113 list contains three kinds of row: roll-up super-categories,
// the ~50 mutually-exclusive "rankable" causes (their label starts with
// '#'), and finer sub-detail. Only the rankable set is meaningful for a
// ranking or a "leading cause" callout, so that's all this module exposes.

const SNAPSHOT_URL = `${import.meta.env.BASE_URL}data/mortality.json`

export async function fetchCausesOfDeath() {
  let res
  try {
    res = await fetch(SNAPSHOT_URL, { headers: { accept: 'application/json' } })
  } catch (err) {
    throw new Error(`Couldn't load the mortality data file: ${err.message}`)
  }
  if (!res.ok) {
    throw new Error(
      `Couldn't load the mortality data file (HTTP ${res.status}). ` +
        `It's generated by the data pipeline — see pipeline/README.md.`
    )
  }

  const raw = await res.json()
  const leading = raw.causes.filter((c) => c.leading)
  const leadingCodes = new Set(leading.map((c) => c.code))

  // Ranked rows per year (rankable causes only). Kept sorted by deaths
  // descending here; the view re-sorts by whichever metric is selected.
  const byYear = {}
  for (const [year, rows] of Object.entries(raw.byYear)) {
    byYear[year] = rows
      .filter((r) => leadingCodes.has(r.code))
      .map((r) => ({
        code: r.code,
        cause: r.name,
        deaths: r.deaths,
        crudeRate: r.crudeRate,
        ageAdjustedRate: r.ageAdjustedRate,
        suppressed: r.suppressed
      }))
  }

  // Per-cause time series, keyed by display name and ALIGNED to the full
  // `years` axis (missing years -> null) so the view can overlay several
  // causes on one chart without re-indexing. A cause that only appears
  // partway through the range (e.g. COVID-19) simply has leading nulls.
  const allYears = raw.years
  const byCause = {}
  for (const c of leading) {
    const s = raw.byCause[`${c.icdVersion}:${c.code}`]
    if (!s) continue
    const at = (arr) => {
      const m = new Map(s.years.map((y, i) => [y, arr[i]]))
      return allYears.map((y) => (m.has(y) ? m.get(y) : null))
    }
    byCause[c.name] = {
      code: c.code,
      years: allYears,
      deaths: at(s.deaths),
      crudeRate: at(s.crudeRate),
      ageAdjustedRate: at(s.ageAdjustedRate)
    }
  }

  const causes = leading.map((c) => c.name).sort((a, b) => a.localeCompare(b))

  return {
    source: raw.source,
    fetchedAt: raw.fetchedAt,
    coverage: raw.coverage,
    years: raw.years,
    causes,
    byYear,
    byCause
  }
}
