// Pipeline: CAUSES OF DEATH — demographic breakdown (Sex / Race)
//
// Source: the static snapshot the WONDER pipeline writes to
// /data/mortality_demographic.json (see pipeline/). That's CDC WONDER's
// "Underlying Cause of Death" (D76), national, grouped by year × the NCHS
// 113-cause list × one demographic axis at a time — one axis per fetch era
// (icd10_sex, icd10_race).
//
// Kept in its own file/table/snapshot so the main mortality path is
// untouched. Until the pipeline eras are run, the committed file is a stub
// with `dimensions: {}` — `available` comes back false and the Causes of
// Death page just hides the Breakdown control.
//
// WONDER suppresses any subgroup cell with 1–9 deaths, so rarer causes have
// missing subgroups. Race comparisons should use the age-adjusted rate —
// crude rate mostly reflects differing age structures.

const SNAPSHOT_URL = `${import.meta.env.BASE_URL}data/mortality_demographic.json`

export async function fetchCauseBreakdown() {
  let res
  try {
    res = await fetch(SNAPSHOT_URL, { headers: { accept: 'application/json' } })
  } catch (err) {
    throw new Error(`Couldn't load the breakdown data file: ${err.message}`)
  }
  if (!res.ok) {
    // A missing file shouldn't break the page — treat it as "no breakdown".
    if (res.status === 404) return { available: false, dimensionKeys: [] }
    throw new Error(
      `Couldn't load the breakdown data file (HTTP ${res.status}). ` +
        `It's generated by the data pipeline — see pipeline/README.md.`
    )
  }

  const raw = await res.json()
  const dimensionKeys = Object.keys(raw.dimensions ?? {})
  if (dimensionKeys.length === 0) {
    return { available: false, dimensionKeys: [], source: raw.source }
  }

  const years = raw.years ?? []
  const alignTo = (subYears, arr) => {
    const m = new Map(subYears.map((y, i) => [y, arr[i]]))
    return years.map((y) => (m.has(y) ? m.get(y) : null))
  }

  const dimensions = {}
  for (const key of dimensionKeys) {
    const d = raw.dimensions[key]

    // byCause: align every subgroup's series to the shared `years` axis so
    // the trend chart can overlay them without re-indexing.
    const byCause = {}
    for (const [code, c] of Object.entries(d.byCause ?? {})) {
      const subgroups = {}
      for (const [sg, s] of Object.entries(c.subgroups ?? {})) {
        subgroups[sg] = {
          deaths: alignTo(s.years, s.deaths),
          crudeRate: alignTo(s.years, s.crudeRate),
          ageAdjustedRate: alignTo(s.years, s.ageAdjustedRate)
        }
      }
      byCause[code] = { name: c.name, leading: c.leading, subgroups }
    }

    dimensions[key] = {
      subgroups: d.subgroups ?? [],
      byYear: d.byYear ?? {},
      byCause
    }
  }

  return {
    available: true,
    source: raw.source,
    fetchedAt: raw.fetchedAt,
    coverage: raw.coverage,
    years,
    dimensionKeys,
    dimensions
  }
}
