// Pipeline: HISTORICAL ANNUAL DEATHS (Death Statistics "Annual Deaths" chart)
//
// Source: the static snapshot the WONDER pipeline writes to
// /data/mortality.json (see pipeline/). It carries one synthetic
// "All causes" row per year:
//   - 1968–1978 from D74 + 1979–1998 from D16 "Compressed Mortality" (eras
//     icd8_total / icd9_total, grouped by Year only) — finalized, with
//     crude and age-adjusted rate.
//   - 1999–2020 from D76 "Underlying Cause of Death" (era icd10_total) —
//     finalized NCHS figures.
//   - 2021–present from D176 "Provisional Mortality Statistics" (era
//     provisional) — CDC provisional counts; close to final but subject to
//     small revision, and the most recent year may be a month or two short.
//
// The age-adjusted RATE is extended past the ends of the WONDER snapshot
// from two CDC Socrata series, both age-adjusted to the same 2000 US
// standard population, so the joins are seamless (overlap years match to
// ~0.1 per 100,000):
//   - back to 1900   w9j2-ggv5 "Death rates and life expectancy at birth"
//                    (All Races / Both Sexes) — the only pre-1968 source.
//   - forward        489q-934x "VSRR Quarterly provisional estimates for
//                    selected indicators of mortality" — All causes,
//                    Age-adjusted, "12 months ending with quarter", Q4 row
//                    = the calendar-year provisional rate. A FALLBACK only:
//                    the D176 `provisional` era now carries an age-adjusted
//                    rate on the all-cause row, so this fills a year only
//                    if a stale snapshot is missing it.
// Death COUNTS (and the crude rate) still start at 1968: WONDER has no
// earlier count, and you can't recover a count from an age-adjusted rate.
// Pre-1933 the figure covers the expanding US death-registration area
// rather than every state.

import { socrataQuery } from './socrata.js'

const SNAPSHOT_URL = `${import.meta.env.BASE_URL}data/mortality.json`
const HIST_RATE_ID = 'w9j2-ggv5'
const VSRR_RATE_ID = '489q-934x'

// Named by which sources actually contributed years to each series.
function sourceLabel(firstRateYear, firstCountYear, vsrrUsed) {
  const parts = []
  if (firstRateYear <= 1967) {
    parts.push('Death rates & life expectancy since 1900 (NCHS/Socrata w9j2-ggv5, age-adjusted rate)')
  }
  if (firstCountYear <= 1998) parts.push('Compressed Mortality (D74/D16, 1968–1998)')
  parts.push('Underlying Cause of Death (D76, 1999–2020)')
  parts.push('Provisional Mortality Statistics (D176, 2021–present)')
  if (vsrrUsed) {
    parts.push('VSRR quarterly provisional age-adjusted rate (NCHS/Socrata 489q-934x)')
  }
  return `CDC WONDER + CDC Socrata — ${parts.join(' + ')}, national`
}

// D76's finalized range. Later years come from the provisional database.
const FINAL_THROUGH = 2020

export async function fetchHistoricalAnnualDeaths() {
  const [res, histRateRows, vsrrRateRows] = await Promise.all([
    fetch(SNAPSHOT_URL, { headers: { accept: 'application/json' } }).catch((err) => {
      throw new Error(`Couldn't load the mortality data file: ${err.message}`)
    }),
    socrataQuery(HIST_RATE_ID, {
      $select: 'year, mortality',
      $where: "race='All Races' AND sex='Both Sexes'",
      $order: 'year',
      $limit: 5000
    }).catch(() => []),
    socrataQuery(VSRR_RATE_ID, {
      $select: 'year_and_quarter, rate_overall',
      $where:
        "cause_of_death='All causes' AND rate_type='Age-adjusted' " +
        "AND time_period='12 months ending with quarter'",
      $order: 'year_and_quarter',
      $limit: 5000
    }).catch(() => [])
  ])
  if (!res.ok) {
    throw new Error(
      `Couldn't load the mortality data file (HTTP ${res.status}). ` +
        `It's generated by the data pipeline — see pipeline/README.md.`
    )
  }

  const raw = await res.json()

  // WONDER snapshot: count + both rates per year, 1968+.
  const wonder = new Map()
  for (const [year, entries] of Object.entries(raw.byYear ?? {})) {
    const all = (entries ?? []).find((e) => e.code === 'All causes' || e.name === 'All causes')
    if (all && all.deaths != null) {
      wonder.set(Number(year), {
        deaths: all.deaths,
        crudeRate: all.crudeRate ?? null,
        ageAdjustedRate: all.ageAdjustedRate ?? null
      })
    }
  }

  // Historical age-adjusted rate, 1900+, for years before the WONDER
  // snapshot.
  const histRate = new Map()
  for (const r of histRateRows) {
    const y = Number(r.year)
    const v = Number(r.mortality)
    if (Number.isInteger(y) && Number.isFinite(v)) histRate.set(y, v)
  }

  // VSRR provisional age-adjusted rate, for years past the WONDER
  // snapshot's rate coverage. The Q4 "12 months ending with quarter" row
  // is the calendar-year figure; earlier quarters are rolling 12-month
  // windows that don't line up with a year, so skip them.
  const vsrrRate = new Map()
  for (const r of vsrrRateRows) {
    const [yStr, q] = String(r.year_and_quarter ?? '').split(' ')
    const y = Number(yStr)
    const v = Number(r.rate_overall)
    if (q === 'Q4' && Number.isInteger(y) && Number.isFinite(v)) vsrrRate.set(y, v)
  }

  const years = [...new Set([...histRate.keys(), ...wonder.keys(), ...vsrrRate.keys()])].sort(
    (a, b) => a - b
  )
  let vsrrUsed = false
  const rows = years.map((y) => {
    const w = wonder.get(y)
    let aar = w?.ageAdjustedRate ?? histRate.get(y) ?? null
    if (aar == null && vsrrRate.has(y)) {
      aar = vsrrRate.get(y)
      vsrrUsed = true
    }
    return {
      year: y,
      deaths: w?.deaths ?? null,
      crudeRate: w?.crudeRate ?? null,
      ageAdjustedRate: aar
    }
  })

  const firstCountYear = rows.find((r) => r.deaths != null)?.year ?? 1999
  return {
    source: sourceLabel(rows[0]?.year ?? 1968, firstCountYear, vsrrUsed),
    fetchedAt: raw.fetchedAt,
    years: rows.map((r) => r.year),
    totalDeaths: rows.map((r) => r.deaths),
    crudeRate: rows.map((r) => r.crudeRate),
    ageAdjustedRate: rows.map((r) => r.ageAdjustedRate),
    isProvisional: rows.map((r) => r.year > FINAL_THROUGH),
    firstCountYear
  }
}
