// Suicide, homicide, and overdose deaths — Feature #8 in CLAUDE.md's
// backlog ("Drug overdose / suicide / firearm deaths as first-class
// topics"). Phase 1: suicide, homicide, and the firearm breakdown of each
// all read rows already sitting in the committed /data/mortality.json
// snapshot (the NCHS 113-cause list) — no new pipeline era needed.
//
// "Firearm deaths" here = suicide-by-firearm + homicide-by-firearm. WONDER's
// 113-cause list isolates those two rows but not unintentional or
// undetermined-intent firearm deaths (a smaller slice), so this total runs
// a little low against CDC's own published "firearm deaths" figure, which
// includes those too.
//
// Overdose: the 113-list has no clean "drug overdose" row, only "Accidental
// poisoning and exposure to noxious substances (X40-X49)" — it misses
// poisoning deaths ruled a suicide or of undetermined intent, and includes
// a small number of non-drug poisonings. That's `overdoseProxy` below, kept
// for its long 1999+ run. Phase 2 originally planned a dedicated WONDER
// pull to fix this, but NCHS already publishes the real thing on a
// different Socrata dataset — the same quarterly VSRR release used for
// State Comparison (489q-934x) carries a "Drug overdose" row with the
// actual age-adjusted national rate, no proxy needed. It's `overdoseRate`
// below: shorter (2023+, quarterly) but the genuine CDC definition, so the
// view shows both — the proxy for long-run shape, this for an accurate
// recent trend.

import { socrataQuery } from './socrata.js'

const SNAPSHOT_URL = `${import.meta.env.BASE_URL}data/mortality.json`
const VSRR_DATASET_ID = '489q-934x'

const CAUSE_KEYS = {
  suicide: '10:#Intentional self-harm (suicide) (*U03,X60-X84,Y87.0)',
  suicideFirearm: '10:Intentional self-harm (suicide) by discharge of firearms (X72-X74)',
  homicide: '10:#Assault (homicide) (*U01-*U02,X85-Y09,Y87.1)',
  homicideFirearm: '10:Assault (homicide) by discharge of firearms (*U01.4,X93-X95)',
  overdoseProxy: '10:Accidental poisoning and exposure to noxious substances (X40-X49)'
}

// The last 2 years of the overdose proxy are provisional enough (see
// header note) that they get flagged even more aggressively than the
// usual "provisional" muted point elsewhere on the site.
const OVERDOSE_UNRELIABLE_FROM_END = 2

function pick(raw, key) {
  const c = raw.byCause[key]
  if (!c) return null
  return { years: c.years.map(Number), deaths: c.deaths }
}

// Sum two aligned-by-year series. Missing years on either side -> null
// rather than treating a missing value as zero.
function sum(a, b) {
  if (!a) return b
  if (!b) return a
  const years = a.years
  const bIndex = new Map(b.years.map((y, i) => [y, i]))
  const deaths = years.map((y, i) => {
    const av = a.deaths[i]
    const bi = bIndex.get(y)
    const bv = bi == null ? null : b.deaths[bi]
    return av == null && bv == null ? null : (av ?? 0) + (bv ?? 0)
  })
  return { years, deaths }
}

async function fetchOverdoseRate() {
  let rows
  try {
    rows = await socrataQuery(VSRR_DATASET_ID, {
      $where: "cause_of_death='Drug overdose' AND time_period='12 months ending with quarter' AND rate_type='Age-adjusted'",
      $select: 'year_and_quarter,rate_overall',
      $order: 'year_and_quarter'
    })
  } catch {
    return null // supplementary — the page works without it
  }
  const quarters = []
  const rate = []
  for (const r of rows) {
    if (r.rate_overall == null) continue
    quarters.push(r.year_and_quarter)
    rate.push(Number(r.rate_overall))
  }
  return quarters.length ? { quarters, rate } : null
}

export async function fetchInjuryDeaths() {
  let res
  try {
    res = await fetch(SNAPSHOT_URL, { headers: { accept: 'application/json' } })
  } catch (err) {
    throw new Error(`Couldn't load the mortality data file: ${err.message}`)
  }
  if (!res.ok) {
    throw new Error(
      `Couldn't load the mortality data file (HTTP ${res.status}). ` +
        `It's generated by the data pipeline — see pipeline/README.md.`
    )
  }

  const [raw, overdoseRate] = await Promise.all([res.json(), fetchOverdoseRate()])
  const suicide = pick(raw, CAUSE_KEYS.suicide)
  const suicideFirearm = pick(raw, CAUSE_KEYS.suicideFirearm)
  const homicide = pick(raw, CAUSE_KEYS.homicide)
  const homicideFirearm = pick(raw, CAUSE_KEYS.homicideFirearm)
  const overdoseProxy = pick(raw, CAUSE_KEYS.overdoseProxy)
  const firearmTotal = sum(suicideFirearm, homicideFirearm)

  const overdoseMuted = overdoseProxy
    ? overdoseProxy.years.map((_, i) => i >= overdoseProxy.years.length - OVERDOSE_UNRELIABLE_FROM_END)
    : []

  return {
    source: raw.source,
    fetchedAt: raw.fetchedAt,
    suicide,
    suicideFirearm,
    homicide,
    homicideFirearm,
    firearmTotal,
    overdoseProxy,
    overdoseMuted,
    overdoseRate
  }
}
