// Suicide, homicide, and overdose deaths — Feature #8 in CLAUDE.md's
// backlog ("Drug overdose / suicide / firearm deaths as first-class
// topics"). Phase 1: all of this reads rows already sitting in the
// committed /data/mortality.json snapshot (the NCHS 113-cause list),
// so no new pipeline era was needed for suicide, homicide, or the
// firearm breakdown of each.
//
// "Firearm deaths" here = suicide-by-firearm + homicide-by-firearm. WONDER's
// 113-cause list isolates those two rows but not unintentional or
// undetermined-intent firearm deaths (a smaller slice), so this total runs
// a little low against CDC's own published "firearm deaths" figure, which
// includes those too.
//
// "Overdose" is the roughest part of this module. The only 113-list row
// that gets close is "Accidental poisoning and exposure to noxious
// substances (X40-X49)" — it's NOT the same as CDC's published "drug
// overdose deaths" figure, which also folds in poisoning deaths ruled a
// suicide or of undetermined intent, and (this row) also includes a small
// number of non-drug poisonings (gases, other chemicals). Treat it as a
// placeholder until a dedicated WONDER pull (the "Drug/Alcohol Induced
// Causes" grouping) replaces it — see the Remaining section in CLAUDE.md.
// It's also visibly undercounted in the most recent 1-2 years: overdose
// deaths take longer to certify (pending toxicology), so provisional
// counts run low and get revised up over time — more so than the usual
// provisional lag elsewhere on this site.

const SNAPSHOT_URL = `${import.meta.env.BASE_URL}data/mortality.json`

const CAUSE_KEYS = {
  suicide: '10:#Intentional self-harm (suicide) (*U03,X60-X84,Y87.0)',
  suicideFirearm: '10:Intentional self-harm (suicide) by discharge of firearms (X72-X74)',
  homicide: '10:#Assault (homicide) (*U01-*U02,X85-Y09,Y87.1)',
  homicideFirearm: '10:Assault (homicide) by discharge of firearms (*U01.4,X93-X95)',
  overdoseProxy: '10:Accidental poisoning and exposure to noxious substances (X40-X49)'
}

// The last 2 years of the overdose proxy are provisional enough (see
// header note) that they get flagged even more aggressively than the
// usual "provisional" muted point elsewhere on the site.
const OVERDOSE_UNRELIABLE_FROM_END = 2

function pick(raw, key) {
  const c = raw.byCause[key]
  if (!c) return null
  return { years: c.years.map(Number), deaths: c.deaths }
}

// Sum two aligned-by-year series. Missing years on either side -> null
// rather than treating a missing value as zero.
function sum(a, b) {
  if (!a) return b
  if (!b) return a
  const years = a.years
  const bIndex = new Map(b.years.map((y, i) => [y, i]))
  const deaths = years.map((y, i) => {
    const av = a.deaths[i]
    const bi = bIndex.get(y)
    const bv = bi == null ? null : b.deaths[bi]
    return av == null && bv == null ? null : (av ?? 0) + (bv ?? 0)
  })
  return { years, deaths }
}

export async function fetchInjuryDeaths() {
  let res
  try {
    res = await fetch(SNAPSHOT_URL, { headers: { accept: 'application/json' } })
  } catch (err) {
    throw new Error(`Couldn't load the mortality data file: ${err.message}`)
  }
  if (!res.ok) {
    throw new Error(
      `Couldn't load the mortality data file (HTTP ${res.status}). ` +
        `It's generated by the data pipeline — see pipeline/README.md.`
    )
  }

  const raw = await res.json()
  const suicide = pick(raw, CAUSE_KEYS.suicide)
  const suicideFirearm = pick(raw, CAUSE_KEYS.suicideFirearm)
  const homicide = pick(raw, CAUSE_KEYS.homicide)
  const homicideFirearm = pick(raw, CAUSE_KEYS.homicideFirearm)
  const overdoseProxy = pick(raw, CAUSE_KEYS.overdoseProxy)
  const firearmTotal = sum(suicideFirearm, homicideFirearm)

  const overdoseMuted = overdoseProxy
    ? overdoseProxy.years.map((_, i) => i >= overdoseProxy.years.length - OVERDOSE_UNRELIABLE_FROM_END)
    : []

  return {
    source: raw.source,
    fetchedAt: raw.fetchedAt,
    suicide,
    suicideFirearm,
    homicide,
    homicideFirearm,
    firearmTotal,
    overdoseProxy,
    overdoseMuted
  }
}
