// Pipeline: MONTHLY DEATHS (Death Statistics "Monthly Deaths" chart)
//
// Source: /data/mortality_monthly.json, written by the WONDER pipeline from
// D176 "Provisional Mortality Statistics, 2018 through Last Month" grouped
// by Year x Month — a continuous national all-cause series back to Jan 2018.
//
// Replaces the Socrata table hmz2-vwda, which CDC trimmed to a rolling
// ~18-month window (and stopped refreshing past mid-2024).
//
// Until the pipeline era `monthly` runs, the committed file is a stub with
// an empty `months` array — callers should handle `values.length === 0`.

const SNAPSHOT_URL = `${import.meta.env.BASE_URL}data/mortality_monthly.json`

export async function fetchMonthlyDeaths() {
  let res
  try {
    res = await fetch(SNAPSHOT_URL, { headers: { accept: 'application/json' } })
  } catch (err) {
    throw new Error(`Couldn't load the monthly deaths file: ${err.message}`)
  }
  if (!res.ok) {
    if (res.status === 404) {
      return { source: null, fetchedAt: null, labels: [], values: [], months: [] }
    }
    throw new Error(
      `Couldn't load the monthly deaths file (HTTP ${res.status}). ` +
        `It's generated by the data pipeline — see pipeline/README.md.`
    )
  }

  const raw = await res.json()
  const months = raw.months ?? []

  // D176 is "through last month" — the final month or two are still
  // accumulating late records and read far below the run rate. Flag any
  // trailing month under 80% of the prior 6-month median as incomplete.
  const partial = months.map(() => false)
  if (months.length >= 8) {
    const prior = months.slice(-7, -1).map((m) => m.deaths).filter((v) => v != null).sort((a, b) => a - b)
    const ref = prior.length ? prior[Math.floor(prior.length / 2)] : null
    if (ref) {
      for (let i = months.length - 1; i >= months.length - 3; i--) {
        if (months[i].deaths != null && months[i].deaths < ref * 0.8) partial[i] = true
        else break
      }
    }
  }

  return {
    source: raw.source,
    fetchedAt: raw.fetchedAt,
    labels: months.map((m) => m.label),
    values: months.map((m) => m.deaths),
    partial,
    months
  }
}
