// Pipeline: ANNUAL NATALITY (births + fertility rate over time)
//
// Reads the static snapshot /data/natality.json (WONDER pipeline: D27/D66 +
// D192 provisional + a committed Socrata baseline, 1960–present). Then, only
// for whole calendar years PAST the snapshot's newest year, it rolls up CDC's
// "AH Monthly Provisional Counts" (Socrata hmz2-vwda) to an annual total, so
// the births line can still inch ahead of the pipeline between refreshes.
// Rolled-up years carry a count only (no rate) and are flagged provisional.
//
// D192's newest year is a PARTIAL calendar year ("2026 through June 30"), so
// its total is roughly half a real year. `partial` flags any trailing year
// whose births fall well below the year before it; the view drops those from
// the plotted line and shows the running total as a caption instead.
//
// The crude birth rate (per 1,000 residents) is backfilled from
// births ÷ mortality.json population wherever the natality snapshot lacks it
// (WONDER stopped supplying it after 2018) — flagged `birthRateDerived`. The
// general fertility rate (per 1,000 women 15-44) stops wherever the
// snapshot's `fertilityRate` runs out — WONDER supplies it through 2020;
// past that, pipeline/fetch-census-fertility.js backfills it from the
// Census Bureau's population estimates (women 15-44) for whatever years
// that program has published so far (currently through 2023 — its
// single-year-age/sex release lags the current year by ~2).
//
// Shape:  { source, fetchedAt, coverage:{yearMin,yearMax,note},
//           years:[int], partial:[bool],
//           byYear: { <year>: { births, birthRate, fertilityRate, population,
//                       suppressed, provisional?, partial?, birthRateDerived? } } }

import { socrataQuery } from './socrata.js'

const SNAPSHOT_URL = `${import.meta.env.BASE_URL}data/natality.json`
const MORTALITY_URL = `${import.meta.env.BASE_URL}data/mortality.json`

// The WONDER natality databases stopped supplying the crude birth rate after
// 2018 (D66/D27 give it; D192 provisional has no rate measure). But the
// crude birth rate is just births ÷ resident population × 1,000, and the
// mortality snapshot's "All causes" rows already carry that exact Census
// resident-population estimate per year (it's WONDER's own rate denominator,
// so this reproduces NCHS's published figure to ~0.1). Fill the gap from it.
async function totalPopulationByYear() {
  try {
    const res = await fetch(MORTALITY_URL, { headers: { accept: 'application/json' } })
    if (!res.ok) return new Map()
    const raw = await res.json()
    const out = new Map()
    for (const [year, rows] of Object.entries(raw.byYear ?? {})) {
      const all = (rows ?? []).find((r) => r.name === 'All causes')
      if (all?.population) out.set(Number(year), all.population)
    }
    return out
  } catch {
    return new Map()
  }
}

// A real annual total is never much below the prior year outside catastrophe;
// a mid-year D192 total sits near half. Anything under this fraction of the
// preceding year is treated as an incomplete year.
const PARTIAL_YEAR_RATIO = 0.7

async function monthlyBirthRollup(afterYear) {
  try {
    const rows = await socrataQuery('hmz2-vwda', {
      $select: 'year, count(1) as months, sum(data_value) as births',
      $where:
        "state='UNITED STATES' AND period='Monthly' AND indicator='Number of Live Births'",
      $group: 'year',
      $order: 'year'
    })
    const out = new Map()
    for (const r of rows) {
      const y = Number(r.year)
      // only whole years, and only past what the snapshot already covers
      if (y > afterYear && Number(r.months) >= 12 && Number.isFinite(Number(r.births))) {
        out.set(y, Math.round(Number(r.births)))
      }
    }
    return out
  } catch {
    return new Map()
  }
}

export async function fetchAnnualNatality() {
  let res
  try {
    res = await fetch(SNAPSHOT_URL, { headers: { accept: 'application/json' } })
  } catch (err) {
    throw new Error(`Couldn't load the natality data file: ${err.message}`)
  }
  if (!res.ok) {
    throw new Error(
      `Couldn't load the natality data file (HTTP ${res.status}). ` +
        `It's generated by the data pipeline — see pipeline/README.md.`
    )
  }

  const raw = await res.json()
  const snapshotMax = raw.years.length ? Math.max(...raw.years) : 0
  const [rolled, totalPop] = await Promise.all([
    monthlyBirthRollup(snapshotMax),
    totalPopulationByYear()
  ])

  const byYear = { ...raw.byYear }
  for (const [y, births] of rolled) {
    byYear[y] = {
      births,
      birthRate: null,
      fertilityRate: null,
      population: null,
      suppressed: false,
      provisional: true
    }
  }

  // Backfill the crude birth rate wherever it's missing but we have both a
  // birth count and a resident-population figure.
  for (const [y, rec] of Object.entries(byYear)) {
    const pop = totalPop.get(Number(y))
    if (rec.births != null && rec.birthRate == null && pop) {
      byYear[y] = {
        ...rec,
        birthRate: Math.round((rec.births / pop) * 1000 * 10) / 10,
        birthRateDerived: true
      }
    }
  }

  const years = [...new Set([...raw.years, ...rolled.keys()])].sort((a, b) => a - b)

  // Flag a trailing run of incomplete years (walk back from the newest while
  // each is well under its predecessor). Only the tail can be partial.
  const partialSet = new Set()
  for (let i = years.length - 1; i > 0; i--) {
    const cur = byYear[years[i]]?.births
    const prev = byYear[years[i - 1]]?.births
    if (cur != null && prev > 0 && cur < prev * PARTIAL_YEAR_RATIO) {
      partialSet.add(years[i])
      byYear[years[i]] = { ...byYear[years[i]], partial: true }
    } else {
      break
    }
  }

  const source = rolled.size
    ? `${raw.source}; ${[...rolled.keys()].join(', ')} rolled up from CDC AH Monthly Provisional Counts (Socrata hmz2-vwda)`
    : raw.source

  return {
    source,
    fetchedAt: raw.fetchedAt,
    coverage: { ...raw.coverage, yearMax: years.at(-1) ?? raw.coverage?.yearMax },
    years,
    partial: years.map((y) => partialSet.has(y)),
    births: years.map((y) => byYear[y]?.births ?? null),
    birthRate: years.map((y) => byYear[y]?.birthRate ?? null),
    fertilityRate: years.map((y) => byYear[y]?.fertilityRate ?? null),
    byYear
  }
}
