// Pipeline: ANNUAL NATALITY (births + fertility rate over time)
//
// Reads the static snapshot /data/natality.json — same pattern as
// causesOfDeath.js. The committed baseline is CDC's NCHS "Natality Measures
// by Race" (Socrata 89yk-m38d, All races, 1960–2018). The WONDER natality
// pipeline (databases D149 / D66 / D27, see pipeline/) overwrites it with a
// series that reaches the latest published year and carries the same
// fields.
//
// Shape:  { source, fetchedAt, coverage:{yearMin,yearMax,note},
//           years:[int],
//           byYear: { <year>: { births, birthRate, fertilityRate,
//                               population, suppressed } } }

const SNAPSHOT_URL = `${import.meta.env.BASE_URL}data/natality.json`

export async function fetchAnnualNatality() {
  let res
  try {
    res = await fetch(SNAPSHOT_URL, { headers: { accept: 'application/json' } })
  } catch (err) {
    throw new Error(`Couldn't load the natality data file: ${err.message}`)
  }
  if (!res.ok) {
    throw new Error(
      `Couldn't load the natality data file (HTTP ${res.status}). ` +
        `It's generated by the data pipeline — see pipeline/README.md.`
    )
  }

  const raw = await res.json()
  const years = raw.years.slice().sort((a, b) => a - b)

  return {
    source: raw.source,
    fetchedAt: raw.fetchedAt,
    coverage: raw.coverage,
    years,
    births: years.map((y) => raw.byYear[y]?.births ?? null),
    birthRate: years.map((y) => raw.byYear[y]?.birthRate ?? null),
    fertilityRate: years.map((y) => raw.byYear[y]?.fertilityRate ?? null),
    byYear: raw.byYear
  }
}
