// Pipeline: US POPULATION BY CENSUS REGION (Northeast/Midwest/South/West)
//
// Reads the static snapshot /data/population_by_region.json, produced by
// pipeline/fetch-census-population.js from the Census Bureau's Population
// Estimates Program. These are real Census-published region totals (a
// sum), not derived from the state-level death rates elsewhere on this
// page — unlike those rates, population is additive, so no weighting
// caveat applies here.
//
// Shape:  { source, fetchedAt, coverage:{yearMin,yearMax,note},
//           regions:[string], years:[int], byRegion: { <region>: [int] } }
// (byRegion's arrays are aligned to `years`, ready to hand straight to
// TimeSeriesChart as one series per region.)

const SNAPSHOT_URL = `${import.meta.env.BASE_URL}data/population_by_region.json`

export async function fetchRegionPopulation() {
  let res
  try {
    res = await fetch(SNAPSHOT_URL, { headers: { accept: 'application/json' } })
  } catch (err) {
    throw new Error(`Couldn't load the region population data file: ${err.message}`)
  }
  if (!res.ok) {
    throw new Error(
      `Couldn't load the region population data file (HTTP ${res.status}). ` +
        `It's generated by the data pipeline — see pipeline/README.md.`
    )
  }

  const raw = await res.json()
  return {
    source: raw.source,
    fetchedAt: raw.fetchedAt,
    coverage: raw.coverage,
    regions: raw.regions,
    years: raw.years,
    byRegion: Object.fromEntries(
      raw.regions.map((r) => [r, raw.years.map((y) => raw.byYear[y]?.[r] ?? null)])
    )
  }
}
